function expr = Model(t,in2,in3)
%MODEL
%    EXPR = MODEL(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    31-Aug-2021 09:20:11

A = in2(5,:);
C = in2(6,:);
D = in2(2,:);
E = in2(7,:);
I = in2(3,:);
Q = in2(8,:);
R = in2(1,:);
S = in2(4,:);
param69 = in3(:,1);
param70 = in3(:,2);
param71 = in3(:,3);
param72 = in3(:,4);
param73 = in3(:,5);
param74 = in3(:,6);
param75 = in3(:,7);
param76 = in3(:,8);
param77 = in3(:,9);
param78 = in3(:,10);
param79 = in3(:,11);
t2 = A.*param79;
t3 = I.*param71;
t4 = Q.*param75;
t5 = Q.*param76;
t6 = E.^2;
t7 = S.^2;
t8 = A.*S.*param73;
t9 = A.*S.*param78;
t10 = C.*S.*param73;
t11 = D.*S.*param73;
t12 = E.*S.*param73;
t13 = I.*S.*param70;
t14 = I.*S.*param73;
t15 = Q.*S.*param73;
t16 = R.*S.*param73;
t18 = A+C+D+E+I+Q+R+S;
t17 = param73.*t7;
t19 = 1.0./t18;
expr = [t5;t4;t2-t3+E.*param74;-t19.*(t8+t9+t10+t11+t12+t13+t14+t15+t16+t17+param69.*t7+A.*S.*param69+C.*S.*param69+D.*S.*param69+E.*S.*param69+I.*S.*param69+Q.*S.*param69+R.*S.*param69);-t2+E.*param72;-C.*param77+S.*param69;t19.*(t8+t9+t10+t11+t12+t13+t14+t15+t16+t17-param72.*t6-param74.*t6+C.^2.*param77+A.*C.*param77-A.*E.*param72-A.*E.*param74+C.*D.*param77-C.*E.*param72-C.*E.*param74+C.*E.*param77-D.*E.*param72-D.*E.*param74+C.*I.*param77-E.*I.*param72-E.*I.*param74+C.*Q.*param77+C.*R.*param77+C.*S.*param77-E.*Q.*param72-E.*Q.*param74-E.*R.*param72-E.*R.*param74-E.*S.*param72-E.*S.*param74);t3-t4-t5];
