function expr = Model(t,in2,in3)
%MODEL
%    EXPR = MODEL(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Sep-2021 15:43:10

I_f = in2(5,:);
I_j = in2(1,:);
I_q = in2(6,:);
R = in2(7,:);
R_j = in2(2,:);
S_f = in2(3,:);
S_q = in2(4,:);
param72 = in3(:,1);
param73 = in3(:,2);
param74 = in3(:,3);
param75 = in3(:,4);
param76 = in3(:,5);
param77 = in3(:,6);
param78 = in3(:,7);
param79 = in3(:,8);
t2 = I_f.*param74;
t3 = I_f.*param75;
t4 = I_f.*param78;
t5 = I_j.*param74;
t6 = I_q.*param72;
t7 = I_q.*param74;
t8 = I_q.*param78;
t9 = R.*param76;
t10 = R_j.*param76;
t11 = S_f.*param73;
t12 = S_f.*param75;
t13 = S_q.*param72;
t14 = S_f+1.0;
t15 = I_f+S_f;
t16 = 1.0./t14;
t17 = 1.0./t15;
t18 = I_j+I_q+R+R_j+S_q+t15;
t19 = S_f.*t16;
t20 = I_f.*param77.*t17;
t21 = 1.0./t18;
t22 = S_f.*t21;
t23 = t22.^t20;
t24 = I_f.*param79.*t22.*t23;
t25 = t19.^t24;
t26 = t11.*t25;
expr = [t4-t5+t8;t5-t10;t9+t10-t11-t12+t13+t26;t12-t13;-t2-t3-t4+t6+t11-t26;t3-t6-t7-t8;t2+t7-t9];
